#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.Dashboard.Heatmap.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Pages\CronHeatmap.cshtml"
    using Hangfire.Community.Dashboard.Heatmap;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\CronHeatmap.cshtml"
    using Hangfire.Community.Dashboard.Heatmap.Pages;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Pages\CronHeatmap.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\CronHeatmap.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class CronHeatmap : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Pages\CronHeatmap.cshtml"
  
    Layout = new LayoutPage(Title);
    var apiUrl = $"{Url.To(GlobalConfigurationExtension.RouteBase)}/api/recurring-jobs";


            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n    /* ===== Base Styles ===== */\r\n    .cron-schedule-container {\r\n   " +
"     padding: 20px;\r\n    }\r\n\r\n    .cron-schedule-header {\r\n        display: flex" +
";\r\n        justify-content: space-between;\r\n        align-items: center;\r\n      " +
"  margin-bottom: 20px;\r\n    }\r\n\r\n    .cron-schedule-header h2 {\r\n        margin:" +
" 0;\r\n        color: #333;\r\n    }\r\n\r\n    .cron-schedule-controls {\r\n        displ" +
"ay: flex;\r\n        gap: 10px;\r\n    }\r\n\r\n    /* Timeline */\r\n    .cron-timeline {" +
"\r\n        position: relative;\r\n        background: #f8f9fa;\r\n        border-radi" +
"us: 8px;\r\n        overflow: hidden;\r\n        margin-bottom: 20px;\r\n        borde" +
"r: 1px solid #dee2e6;\r\n    }\r\n\r\n    .cron-timeline-header {\r\n        display: fl" +
"ex;\r\n        background: #343a40;\r\n        color: white;\r\n        font-size: 12p" +
"x;\r\n    }\r\n\r\n    .cron-timeline-job-header {\r\n        width: 200px;\r\n        pad" +
"ding: 8px;\r\n        text-align: center;\r\n        border-right: 2px solid #495057" +
";\r\n    }\r\n\r\n    .cron-hour-label {\r\n        flex: 1;\r\n        text-align: center" +
";\r\n        padding: 8px 0;\r\n        border-right: 1px solid #495057;\r\n    }\r\n\r\n " +
"   .cron-hour-label:last-child {\r\n        border-right: none;\r\n    }\r\n\r\n    .cro" +
"n-job-row {\r\n        display: flex;\r\n        position: relative;\r\n        border" +
"-bottom: 1px solid #dee2e6;\r\n        min-height: 40px;\r\n        background: #fff" +
";\r\n    }\r\n\r\n    .cron-job-name {\r\n        width: 200px;\r\n        padding: 10px;\r" +
"\n        background: #e9ecef;\r\n        font-weight: 500;\r\n        font-size: 13p" +
"x;\r\n        overflow: hidden;\r\n        text-overflow: ellipsis;\r\n        white-s" +
"pace: nowrap;\r\n        border-right: 2px solid #dee2e6;\r\n        display: flex;\r" +
"\n        align-items: center;\r\n        color: #333;\r\n    }\r\n\r\n    .cron-job-time" +
"line {\r\n        flex: 1;\r\n        position: relative;\r\n        display: flex;\r\n " +
"       background: #fff;\r\n    }\r\n\r\n    .cron-hour-cell {\r\n        flex: 1;\r\n    " +
"    position: relative;\r\n        border-right: 1px solid #dee2e6;\r\n    }\r\n\r\n    " +
".cron-hour-cell:last-child {\r\n        border-right: none;\r\n    }\r\n\r\n    .cron-ex" +
"ecution-marker {\r\n        position: absolute;\r\n        width: 12px;\r\n        hei" +
"ght: 12px;\r\n        background: #007bff;\r\n        border-radius: 50%;\r\n        t" +
"op: 50%;\r\n        transform: translate(-50%, -50%);\r\n        cursor: pointer;\r\n " +
"       z-index: 10;\r\n        transition: transform 0.2s, background-color 0.2s;\r" +
"\n        box-shadow: 0 1px 3px rgba(0,0,0,0.2);\r\n    }\r\n\r\n    .cron-execution-ma" +
"rker:hover {\r\n        transform: translate(-50%, -50%) scale(1.3);\r\n        back" +
"ground: #0056b3;\r\n    }\r\n\r\n    .cron-execution-marker.past {\r\n        background" +
": #6c757d;\r\n    }\r\n\r\n    .cron-execution-marker.upcoming {\r\n        background: " +
"#28a745;\r\n    }\r\n\r\n    /* Tooltip */\r\n    .cron-tooltip {\r\n        position: fix" +
"ed;\r\n        background: #343a40;\r\n        color: white;\r\n        padding: 8px 1" +
"2px;\r\n        border-radius: 4px;\r\n        font-size: 12px;\r\n        z-index: 10" +
"00;\r\n        pointer-events: none;\r\n        white-space: nowrap;\r\n        box-sh" +
"adow: 0 2px 8px rgba(0,0,0,0.2);\r\n        display: none;\r\n    }\r\n\r\n    .cron-too" +
"ltip.visible {\r\n        display: block;\r\n    }\r\n\r\n    .cron-tooltip::after {\r\n  " +
"      content: \'\';\r\n        position: absolute;\r\n        top: 100%;\r\n        lef" +
"t: 50%;\r\n        margin-left: -5px;\r\n        border-width: 5px;\r\n        border-" +
"style: solid;\r\n        border-color: #343a40 transparent transparent transparent" +
";\r\n    }\r\n\r\n    /* Current time indicator */\r\n    .cron-current-time {\r\n        " +
"position: absolute;\r\n        top: 0;\r\n        bottom: 0;\r\n        width: 2px;\r\n " +
"       background: #dc3545;\r\n        z-index: 5;\r\n    }\r\n\r\n    .cron-current-tim" +
"e::before {\r\n        content: \'NOW\';\r\n        position: absolute;\r\n        top: " +
"-20px;\r\n        left: 50%;\r\n        transform: translateX(-50%);\r\n        font-s" +
"ize: 10px;\r\n        color: #dc3545;\r\n        font-weight: bold;\r\n    }\r\n\r\n    /*" +
" Legend */\r\n    .cron-legend {\r\n        display: flex;\r\n        gap: 20px;\r\n    " +
"    padding: 10px 20px;\r\n        background: #f8f9fa;\r\n        border-radius: 4p" +
"x;\r\n        margin-bottom: 20px;\r\n        border: 1px solid #dee2e6;\r\n    }\r\n\r\n " +
"   .cron-legend-item {\r\n        display: flex;\r\n        align-items: center;\r\n  " +
"      gap: 8px;\r\n        font-size: 13px;\r\n        color: #333;\r\n    }\r\n\r\n    .c" +
"ron-legend-marker {\r\n        width: 12px;\r\n        height: 12px;\r\n        border" +
"-radius: 50%;\r\n    }\r\n\r\n    .cron-legend-marker.past {\r\n        background: #6c7" +
"57d;\r\n    }\r\n\r\n    .cron-legend-marker.upcoming {\r\n        background: #28a745;\r" +
"\n    }\r\n\r\n    /* States */\r\n    .cron-state {\r\n        text-align: center;\r\n    " +
"    padding: 40px;\r\n        display: none;\r\n    }\r\n\r\n    .cron-state.visible {\r\n" +
"        display: block;\r\n    }\r\n\r\n    .cron-loading {\r\n        color: #333;\r\n   " +
" }\r\n\r\n    .cron-no-jobs {\r\n        color: #6c757d;\r\n    }\r\n\r\n    .cron-error {\r\n" +
"        color: #dc3545;\r\n    }\r\n\r\n    /* Heatmap */\r\n    .cron-heatmap {\r\n      " +
"  display: grid;\r\n        grid-template-columns: repeat(24, 1fr);\r\n        gap: " +
"2px;\r\n        margin-bottom: 20px;\r\n    }\r\n\r\n    .cron-heatmap-cell {\r\n        a" +
"spect-ratio: 1;\r\n        border-radius: 4px;\r\n        display: flex;\r\n        al" +
"ign-items: center;\r\n        justify-content: center;\r\n        font-size: 10px;\r\n" +
"        color: white;\r\n        font-weight: bold;\r\n        cursor: pointer;\r\n   " +
"     transition: transform 0.2s;\r\n        background: #e9ecef;\r\n    }\r\n\r\n    .cr" +
"on-heatmap-cell:hover {\r\n        transform: scale(1.1);\r\n    }\r\n\r\n    .cron-heat" +
"map-labels {\r\n        display: flex;\r\n        justify-content: space-between;\r\n " +
"       font-size: 11px;\r\n        color: #6c757d;\r\n    }\r\n\r\n    /* Queue badge */" +
"\r\n    .cron-queue-badge {\r\n        display: inline-block;\r\n        padding: 2px " +
"6px;\r\n        border-radius: 3px;\r\n        font-size: 10px;\r\n        margin-left" +
": 5px;\r\n        background: #6c757d;\r\n        color: white;\r\n    }\r\n\r\n    /* Vie" +
"w toggle */\r\n    .cron-view-toggle {\r\n        margin-bottom: 15px;\r\n    }\r\n\r\n   " +
" .cron-view-toggle .btn {\r\n        margin-right: 5px;\r\n    }\r\n\r\n    /* View pane" +
"ls */\r\n    .cron-view-panel {\r\n        display: none;\r\n    }\r\n\r\n    .cron-view-p" +
"anel.active {\r\n        display: block;\r\n    }\r\n\r\n    /* Jobs table */\r\n    .cron" +
"-jobs-table {\r\n        background: #fff;\r\n        border-radius: 4px;\r\n    }\r\n\r\n" +
"    .cron-jobs-table th {\r\n        background: #f8f9fa;\r\n        color: #333;\r\n " +
"   }\r\n\r\n    .cron-jobs-table td {\r\n        color: #333;\r\n    }\r\n\r\n    .cron-jobs" +
"-table code {\r\n        background: #e9ecef;\r\n        color: #333;\r\n        paddi" +
"ng: 2px 6px;\r\n        border-radius: 3px;\r\n    }\r\n\r\n    .cron-timezone-info {\r\n " +
"       font-size: 12px;\r\n        color: #6c757d;\r\n        margin-bottom: 10px;\r\n" +
"    }\r\n\r\n    /* ===== Dark Mode ===== */\r\n    ");


WriteLiteral("@media (prefers-color-scheme: dark) {\r\n        .cron-schedule-header h2 {\r\n      " +
"      color: #e9ecef;\r\n        }\r\n\r\n        .cron-timeline {\r\n            backgr" +
"ound: #1a1a2e;\r\n            border-color: #2d2d44;\r\n        }\r\n\r\n        .cron-t" +
"imeline-header {\r\n            background: #16213e;\r\n        }\r\n\r\n        .cron-t" +
"imeline-job-header {\r\n            border-color: #2d2d44;\r\n        }\r\n\r\n        ." +
"cron-hour-label {\r\n            border-color: #2d2d44;\r\n        }\r\n\r\n        .cro" +
"n-job-row {\r\n            border-color: #2d2d44;\r\n            background: #1a1a2e" +
";\r\n        }\r\n\r\n        .cron-job-name {\r\n            background: #16213e;\r\n    " +
"        border-color: #2d2d44;\r\n            color: #e9ecef;\r\n        }\r\n\r\n      " +
"  .cron-job-timeline {\r\n            background: #1a1a2e;\r\n        }\r\n\r\n        ." +
"cron-hour-cell {\r\n            border-color: #2d2d44;\r\n        }\r\n\r\n        .cron" +
"-execution-marker {\r\n            background: #4dabf7;\r\n            box-shadow: 0" +
" 1px 3px rgba(0,0,0,0.4);\r\n        }\r\n\r\n        .cron-execution-marker:hover {\r\n" +
"            background: #74c0fc;\r\n        }\r\n\r\n        .cron-execution-marker.pa" +
"st {\r\n            background: #868e96;\r\n        }\r\n\r\n        .cron-execution-mar" +
"ker.upcoming {\r\n            background: #51cf66;\r\n        }\r\n\r\n        .cron-too" +
"ltip {\r\n            background: #16213e;\r\n            color: #e9ecef;\r\n         " +
"   box-shadow: 0 2px 8px rgba(0,0,0,0.4);\r\n        }\r\n\r\n        .cron-tooltip::a" +
"fter {\r\n            border-color: #16213e transparent transparent transparent;\r\n" +
"        }\r\n\r\n        .cron-current-time {\r\n            background: #ff6b6b;\r\n   " +
"     }\r\n\r\n        .cron-current-time::before {\r\n            color: #ff6b6b;\r\n   " +
"     }\r\n\r\n        .cron-legend {\r\n            background: #1a1a2e;\r\n            " +
"border-color: #2d2d44;\r\n        }\r\n\r\n        .cron-legend-item {\r\n            co" +
"lor: #e9ecef;\r\n        }\r\n\r\n        .cron-legend-marker.upcoming {\r\n            " +
"background: #51cf66;\r\n        }\r\n\r\n        .cron-legend-marker.past {\r\n         " +
"   background: #868e96;\r\n        }\r\n\r\n        .cron-loading {\r\n            color" +
": #e9ecef;\r\n        }\r\n\r\n        .cron-no-jobs {\r\n            color: #868e96;\r\n " +
"       }\r\n\r\n        .cron-error {\r\n            color: #ff6b6b;\r\n        }\r\n\r\n   " +
"     .cron-heatmap-cell {\r\n            background: #2d2d44;\r\n        }\r\n\r\n      " +
"  .cron-heatmap-labels {\r\n            color: #868e96;\r\n        }\r\n\r\n        .cro" +
"n-queue-badge {\r\n            background: #495057;\r\n            color: #e9ecef;\r\n" +
"        }\r\n\r\n        .cron-jobs-table {\r\n            background: #1a1a2e;\r\n     " +
"   }\r\n\r\n        .cron-jobs-table th {\r\n            background: #16213e;\r\n       " +
"     color: #e9ecef;\r\n            border-color: #2d2d44;\r\n        }\r\n\r\n        ." +
"cron-jobs-table td {\r\n            color: #e9ecef;\r\n            border-color: #2d" +
"2d44;\r\n        }\r\n\r\n        .cron-jobs-table code {\r\n            background: #2d" +
"2d44;\r\n            color: #4dabf7;\r\n        }\r\n\r\n        .cron-jobs-table tr:nth" +
"-child(even) {\r\n            background: #16213e;\r\n        }\r\n\r\n        .cron-job" +
"s-table tr:nth-child(odd) {\r\n            background: #1a1a2e;\r\n        }\r\n\r\n    " +
"    .cron-jobs-table .label-default {\r\n            background: #495057;\r\n       " +
"     color: #e9ecef;\r\n        }\r\n\r\n        .cron-schedule-container h4 {\r\n      " +
"      color: #e9ecef;\r\n        }\r\n\r\n        .cron-timezone-info {\r\n            c" +
"olor: #868e96;\r\n        }\r\n    }\r\n</style>\r\n\r\n<div class=\"cron-schedule-containe" +
"r\">\r\n    <!-- Header -->\r\n    <div class=\"cron-schedule-header\">\r\n        <h2>");


            
            #line 499 "..\..\Pages\CronHeatmap.cshtml"
       Write(Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n        <div class=\"cron-schedule-controls\">\r\n            <button class=\"b" +
"tn btn-sm btn-default\" id=\"cron-refresh-btn\">\r\n                <span class=\"glyp" +
"hicon glyphicon-refresh\"></span> Refresh\r\n            </button>\r\n        </div>\r" +
"\n    </div>\r\n\r\n    <!-- Timezone Info -->\r\n    <div class=\"cron-timezone-info\" i" +
"d=\"cron-timezone-info\"></div>\r\n\r\n    <!-- Legend -->\r\n    <div class=\"cron-legen" +
"d\">\r\n        <div class=\"cron-legend-item\">\r\n            <div class=\"cron-legend" +
"-marker past\"></div>\r\n            <span>Past Execution</span>\r\n        </div>\r\n " +
"       <div class=\"cron-legend-item\">\r\n            <div class=\"cron-legend-marke" +
"r upcoming\"></div>\r\n            <span>Upcoming Execution</span>\r\n        </div>\r" +
"\n    </div>\r\n\r\n    <!-- View Toggle -->\r\n    <div class=\"cron-view-toggle\">\r\n   " +
"     <button class=\"btn btn-sm btn-primary\" id=\"cron-btn-timeline\">Timeline View" +
"</button>\r\n        <button class=\"btn btn-sm btn-default\" id=\"cron-btn-heatmap\">" +
"Heatmap View</button>\r\n    </div>\r\n\r\n    <!-- States -->\r\n    <div class=\"cron-s" +
"tate cron-loading visible\" id=\"cron-loading\">\r\n        <span class=\"glyphicon gl" +
"yphicon-refresh glyphicon-spin\"></span> Loading schedule...\r\n    </div>\r\n    <di" +
"v class=\"cron-state cron-error\" id=\"cron-error\"></div>\r\n    <div class=\"cron-sta" +
"te cron-no-jobs\" id=\"cron-no-jobs\">No recurring jobs found.</div>\r\n\r\n    <!-- Ti" +
"meline View -->\r\n    <div class=\"cron-view-panel\" id=\"cron-view-timeline\">\r\n    " +
"    <div class=\"cron-timeline\" id=\"cron-timeline\">\r\n            <div class=\"cron" +
"-timeline-header\">\r\n                <div class=\"cron-timeline-job-header\">Job</d" +
"iv>\r\n");


            
            #line 540 "..\..\Pages\CronHeatmap.cshtml"
                 for (int h = 0; h < 24; h++)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"cron-hour-label\">");


            
            #line 542 "..\..\Pages\CronHeatmap.cshtml"
                                            Write(h.ToString("00"));

            
            #line default
            #line hidden
WriteLiteral(":00</div>\r\n");


            
            #line 543 "..\..\Pages\CronHeatmap.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral(@"            </div>
            <div id=""cron-timeline-body""></div>
            <div class=""cron-current-time"" id=""cron-current-time""></div>
        </div>
    </div>

    <!-- Heatmap View -->
    <div class=""cron-view-panel"" id=""cron-view-heatmap"">
        <h4>Execution Density by Hour (Local Time)</h4>
        <div class=""cron-heatmap"" id=""cron-heatmap"">
");


            
            #line 554 "..\..\Pages\CronHeatmap.cshtml"
             for (int h = 0; h < 24; h++)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"cron-heatmap-cell\" data-hour=\"");


            
            #line 556 "..\..\Pages\CronHeatmap.cshtml"
                                                     Write(h);

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 556 "..\..\Pages\CronHeatmap.cshtml"
                                                                Write(h.ToString("00"));

            
            #line default
            #line hidden
WriteLiteral(":00 - 0 execution(s)\"></div>\r\n");


            
            #line 557 "..\..\Pages\CronHeatmap.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <div class=\"cron-heatmap-labels\">\r\n");


            
            #line 560 "..\..\Pages\CronHeatmap.cshtml"
             for (int h = 0; h < 24; h += 3)
            {

            
            #line default
            #line hidden
WriteLiteral("                <span>");


            
            #line 562 "..\..\Pages\CronHeatmap.cshtml"
                 Write(h.ToString("00"));

            
            #line default
            #line hidden
WriteLiteral(":00</span>\r\n");


            
            #line 563 "..\..\Pages\CronHeatmap.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"        </div>

        <h4 style=""margin-top: 30px;"">Recurring Jobs</h4>
        <table class=""table table-striped cron-jobs-table"">
            <thead>
                <tr>
                    <th>Job ID</th>
                    <th>Cron Expression</th>
                    <th>Queue</th>
                    <th>Executions Today</th>
                    <th>Next Execution</th>
                </tr>
            </thead>
            <tbody id=""cron-jobs-table-body""></tbody>
        </table>
    </div>

    <!-- Tooltip -->
    <div class=""cron-tooltip"" id=""cron-tooltip""></div>
</div>

<script>
(function() {
    var apiUrl = '");


            
            #line 587 "..\..\Pages\CronHeatmap.cshtml"
             Write(apiUrl);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    var jobsData = [];\r\n    var currentView = \'timeline\';\r\n\r\n    // DOM refer" +
"ences\r\n    var loading = document.getElementById(\'cron-loading\');\r\n    var error" +
" = document.getElementById(\'cron-error\');\r\n    var noJobs = document.getElementB" +
"yId(\'cron-no-jobs\');\r\n    var timelineView = document.getElementById(\'cron-view-" +
"timeline\');\r\n    var heatmapView = document.getElementById(\'cron-view-heatmap\');" +
"\r\n    var timelineBody = document.getElementById(\'cron-timeline-body\');\r\n    var" +
" heatmapCells = document.querySelectorAll(\'.cron-heatmap-cell\');\r\n    var tableB" +
"ody = document.getElementById(\'cron-jobs-table-body\');\r\n    var currentTimeEl = " +
"document.getElementById(\'cron-current-time\');\r\n    var tooltip = document.getEle" +
"mentById(\'cron-tooltip\');\r\n    var btnTimeline = document.getElementById(\'cron-b" +
"tn-timeline\');\r\n    var btnHeatmap = document.getElementById(\'cron-btn-heatmap\')" +
";\r\n    var refreshBtn = document.getElementById(\'cron-refresh-btn\');\r\n    var ti" +
"mezoneInfo = document.getElementById(\'cron-timezone-info\');\r\n\r\n    function init" +
"() {\r\n        displayTimezoneInfo();\r\n        loadData();\r\n        setInterval(u" +
"pdateCurrentTime, 60000);\r\n        \r\n        btnTimeline.addEventListener(\'click" +
"\', function() { switchView(\'timeline\'); });\r\n        btnHeatmap.addEventListener" +
"(\'click\', function() { switchView(\'heatmap\'); });\r\n        refreshBtn.addEventLi" +
"stener(\'click\', function() { showLoading(); loadData(); });\r\n    }\r\n\r\n    functi" +
"on displayTimezoneInfo() {\r\n        var tz = Intl.DateTimeFormat().resolvedOptio" +
"ns().timeZone;\r\n        var offset = new Date().getTimezoneOffset();\r\n        va" +
"r offsetHours = Math.abs(Math.floor(offset / 60));\r\n        var offsetMins = Mat" +
"h.abs(offset % 60);\r\n        var offsetSign = offset <= 0 ? \'+\' : \'-\';\r\n        " +
"var offsetStr = \'UTC\' + offsetSign + pad(offsetHours) + \':\' + pad(offsetMins);\r\n" +
"        timezoneInfo.textContent = \'Displaying times in your local timezone: \' +" +
" tz + \' (\' + offsetStr + \')\';\r\n    }\r\n\r\n    function loadData() {\r\n        var x" +
"hr = new XMLHttpRequest();\r\n        var tzOffset = new Date().getTimezoneOffset(" +
");\r\n        xhr.open(\'GET\', apiUrl + \'?tzOffset=\' + tzOffset, true);\r\n        xh" +
"r.onreadystatechange = function() {\r\n            if (xhr.readyState === 4) {\r\n  " +
"              if (xhr.status === 200) {\r\n                    try {\r\n            " +
"            var data = JSON.parse(xhr.responseText);\r\n                        jo" +
"bsData = data.jobs || [];\r\n                        render();\r\n                  " +
"  } catch (e) {\r\n                        showError(\'Failed to parse response: \' " +
"+ e.message);\r\n                    }\r\n                } else {\r\n                " +
"    showError(\'Failed to load data: \' + xhr.statusText);\r\n                }\r\n   " +
"         }\r\n        };\r\n        xhr.send();\r\n    }\r\n\r\n    function render() {\r\n " +
"       hideStates();\r\n        \r\n        if (jobsData.length === 0) {\r\n          " +
"  noJobs.classList.add(\'visible\');\r\n            return;\r\n        }\r\n\r\n        re" +
"nderTimeline();\r\n        renderHeatmap();\r\n        showView();\r\n        updateCu" +
"rrentTime();\r\n    }\r\n\r\n    function renderTimeline() {\r\n        var html = \'\';\r\n" +
"        var now = new Date();\r\n\r\n        for (var i = 0; i < jobsData.length; i+" +
"+) {\r\n            var job = jobsData[i];\r\n            html += \'<div class=\"cron-" +
"job-row\">\';\r\n            html += \'<div class=\"cron-job-name\" title=\"\' + esc(job." +
"id) + \'\">\' + esc(job.id);\r\n            html += \'<span class=\"cron-queue-badge\">\'" +
" + esc(job.queue) + \'</span></div>\';\r\n            html += \'<div class=\"cron-job-" +
"timeline\">\';\r\n\r\n            for (var h = 0; h < 24; h++) {\r\n                html" +
" += \'<div class=\"cron-hour-cell\"></div>\';\r\n            }\r\n\r\n            for (var" +
" j = 0; j < job.executions.length; j++) {\r\n                var execTime = new Da" +
"te(job.executions[j]);\r\n                \r\n                var hourOfDay = execTi" +
"me.getHours() + (execTime.getMinutes() / 60);\r\n                var leftPercent =" +
" (hourOfDay / 24) * 100;\r\n                \r\n                var isPast = execTim" +
"e.getTime() < now.getTime();\r\n                var cls = isPast ? \'past\' : \'upcom" +
"ing\';\r\n\r\n                html += \'<div class=\"cron-execution-marker \' + cls + \'\"" +
" style=\"left:\' + leftPercent + \'%;\" \';\r\n                html += \'data-job=\"\' + e" +
"sc(job.id) + \'\" data-time=\"\' + execTime.toISOString() + \'\" \';\r\n                h" +
"tml += \'data-cron=\"\' + esc(job.cron) + \'\"></div>\';\r\n            }\r\n\r\n           " +
" html += \'</div></div>\';\r\n        }\r\n\r\n        timelineBody.innerHTML = html;\r\n\r" +
"\n        var markers = timelineBody.querySelectorAll(\'.cron-execution-marker\');\r" +
"\n        for (var k = 0; k < markers.length; k++) {\r\n            markers[k].addE" +
"ventListener(\'mouseenter\', showTooltip);\r\n            markers[k].addEventListene" +
"r(\'mouseleave\', hideTooltip);\r\n        }\r\n    }\r\n\r\n    function renderHeatmap() " +
"{\r\n        var hourCounts = [];\r\n        for (var i = 0; i < 24; i++) hourCounts" +
"[i] = 0;\r\n\r\n        for (var i = 0; i < jobsData.length; i++) {\r\n            for" +
" (var j = 0; j < jobsData[i].executions.length; j++) {\r\n                var exec" +
"Time = new Date(jobsData[i].executions[j]);\r\n                var h = execTime.ge" +
"tHours();\r\n                hourCounts[h]++;\r\n            }\r\n        }\r\n\r\n       " +
" var max = Math.max.apply(null, hourCounts) || 1;\r\n\r\n        for (var i = 0; i <" +
" heatmapCells.length; i++) {\r\n            var cell = heatmapCells[i];\r\n         " +
"   var hour = parseInt(cell.getAttribute(\'data-hour\'), 10);\r\n            var cou" +
"nt = hourCounts[hour];\r\n            var intensity = count / max;\r\n\r\n            " +
"if (count > 0) {\r\n                cell.style.backgroundColor = getHeatmapColor(i" +
"ntensity);\r\n                cell.textContent = count;\r\n            } else {\r\n   " +
"             cell.style.backgroundColor = \'\';\r\n                cell.textContent " +
"= \'\';\r\n            }\r\n            cell.title = pad(hour) + \':00 - \' + count + \' " +
"execution(s)\';\r\n        }\r\n\r\n        var tableHtml = \'\';\r\n        for (var i = 0" +
"; i < jobsData.length; i++) {\r\n            var job = jobsData[i];\r\n            t" +
"ableHtml += \'<tr>\';\r\n            tableHtml += \'<td>\' + esc(job.id) + \'</td>\';\r\n " +
"           tableHtml += \'<td><code>\' + esc(job.cron) + \'</code></td>\';\r\n        " +
"    tableHtml += \'<td><span class=\"label label-default\">\' + esc(job.queue) + \'</" +
"span></td>\';\r\n            tableHtml += \'<td>\' + job.executions.length + \'</td>\';" +
"\r\n            tableHtml += \'<td>\' + (job.nextExecution ? formatDateTime(new Date" +
"(job.nextExecution)) : \'N/A\') + \'</td>\';\r\n            tableHtml += \'</tr>\';\r\n   " +
"     }\r\n        tableBody.innerHTML = tableHtml;\r\n    }\r\n\r\n    function getHeatm" +
"apColor(intensity) {\r\n        var r, g, b;\r\n        \r\n        if (intensity <= 0" +
".25) {\r\n            r = Math.round(76 + (180 * (intensity / 0.25)));\r\n          " +
"  g = 175;\r\n            b = 80;\r\n        } else if (intensity <= 0.5) {\r\n       " +
"     var t = (intensity - 0.25) / 0.25;\r\n            r = Math.round(180 + (75 * " +
"t));\r\n            g = Math.round(175 + (30 * t));\r\n            b = Math.round(80" +
" - (40 * t));\r\n        } else if (intensity <= 0.75) {\r\n            var t = (int" +
"ensity - 0.5) / 0.25;\r\n            r = 255;\r\n            g = Math.round(205 - (1" +
"00 * t));\r\n            b = Math.round(40 - (20 * t));\r\n        } else {\r\n       " +
"     var t = (intensity - 0.75) / 0.25;\r\n            r = 255;\r\n            g = M" +
"ath.round(105 - (75 * t));\r\n            b = Math.round(20 + (30 * t));\r\n        " +
"}\r\n        \r\n        return \'rgb(\' + r + \',\' + g + \',\' + b + \')\';\r\n    }\r\n\r\n    " +
"function updateCurrentTime() {\r\n        var timeline = document.getElementById(\'" +
"cron-timeline\');\r\n        if (!timeline || jobsData.length === 0) return;\r\n\r\n   " +
"     var now = new Date();\r\n        var nowHour = now.getHours() + (now.getMinut" +
"es() / 60);\r\n        var width = timeline.offsetWidth - 200;\r\n        currentTim" +
"eEl.style.left = (200 + (nowHour / 24) * width) + \'px\';\r\n    }\r\n\r\n    function s" +
"howTooltip(e) {\r\n        var el = e.target;\r\n        var execTime = new Date(el." +
"getAttribute(\'data-time\'));\r\n        tooltip.innerHTML = \'<strong>\' + esc(el.get" +
"Attribute(\'data-job\')) + \'</strong><br>\' +\r\n            \'Time: \' + formatDateTim" +
"e(execTime) + \'<br>\' +\r\n            \'Cron: \' + esc(el.getAttribute(\'data-cron\'))" +
";\r\n\r\n        var rect = el.getBoundingClientRect();\r\n        tooltip.classList.a" +
"dd(\'visible\');\r\n        tooltip.style.left = (rect.left + rect.width / 2 - toolt" +
"ip.offsetWidth / 2) + \'px\';\r\n        tooltip.style.top = (rect.top - tooltip.off" +
"setHeight - 10) + \'px\';\r\n    }\r\n\r\n    function hideTooltip() {\r\n        tooltip." +
"classList.remove(\'visible\');\r\n    }\r\n\r\n    function switchView(view) {\r\n        " +
"currentView = view;\r\n        btnTimeline.className = \'btn btn-sm \' + (view === \'" +
"timeline\' ? \'btn-primary\' : \'btn-default\');\r\n        btnHeatmap.className = \'btn" +
" btn-sm \' + (view === \'heatmap\' ? \'btn-primary\' : \'btn-default\');\r\n        showV" +
"iew();\r\n    }\r\n\r\n    function showView() {\r\n        timelineView.className = \'cr" +
"on-view-panel\' + (currentView === \'timeline\' ? \' active\' : \'\');\r\n        heatmap" +
"View.className = \'cron-view-panel\' + (currentView === \'heatmap\' ? \' active\' : \'\'" +
");\r\n    }\r\n\r\n    function showLoading() {\r\n        hideStates();\r\n        loadin" +
"g.classList.add(\'visible\');\r\n    }\r\n\r\n    function showError(msg) {\r\n        hid" +
"eStates();\r\n        error.textContent = msg;\r\n        error.classList.add(\'visib" +
"le\');\r\n    }\r\n\r\n    function hideStates() {\r\n        loading.classList.remove(\'v" +
"isible\');\r\n        error.classList.remove(\'visible\');\r\n        noJobs.classList." +
"remove(\'visible\');\r\n    }\r\n\r\n    function esc(text) {\r\n        if (!text) return" +
" \'\';\r\n        var div = document.createElement(\'div\');\r\n        div.textContent " +
"= text;\r\n        return div.innerHTML;\r\n    }\r\n\r\n    function pad(n) {\r\n        " +
"return n < 10 ? \'0\' + n : n;\r\n    }\r\n\r\n    function formatTime(d) {\r\n        ret" +
"urn pad(d.getHours()) + \':\' + pad(d.getMinutes()) + \':\' + pad(d.getSeconds());\r\n" +
"    }\r\n\r\n    function formatDateTime(d) {\r\n        return pad(d.getDate()) + \'/\'" +
" + pad(d.getMonth() + 1) + \'/\' + d.getFullYear() + \' \' + formatTime(d);\r\n    }\r\n" +
"\r\n    if (document.readyState === \'loading\') {\r\n        document.addEventListene" +
"r(\'DOMContentLoaded\', init);\r\n    } else {\r\n        init();\r\n    }\r\n})();\r\n</scr" +
"ipt>\r\n");


        }
    }
}
#pragma warning restore 1591
